### ISSUE TITLE
It shows error in the log but the plugin works

### ISSUE THREAD

**Issue by 97carmine** [jellyfin/jellyfin-plugin-reports#10]
Every time Jellyfin (10.3.5) starts, I see the following in the log:

```
[2019-06-25 21:21:14.048 +02:00] [ERR] Failed to load assembly "/var/lib/jellyfin/plugins/PlaybackReporting/Jellyfin.Plugin.PlaybackReporting.dll"
System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
```

But the plugin works.

**Comment by anthonylavado** [comment]
Do you have more than one version in the `/var/lib/jellyfin/plugins/` folder? Maybe from an older update when we switched how some plugins were stored...

**Comment by 97carmine** [comment]
That was the problem, there was a folder called `PlaybackReporting`, it was deleted and the error no longer appears.
Thank you.
