### ISSUE TITLE
Jellyfin 10.4.3 - Reports Version 3 not working

### ISSUE THREAD

**Issue by gimmearmdockers** [jellyfin/jellyfin-plugin-reports#12]
Running Jellyfin on a Raspberry Pi 4.

Version: 10.4.3
Operating System: Linux
Architecture: Arm

Plugin installs with no errors, but when trying to run a report gives a blank page with this error text when clicking either the Excel or CSV buttons:
Method not found: '!0[] MediaBrowser.Model.Querying.QueryResult`1.get_Items()'.

Full portion of the log:

> [ERR] Error processing request
System.MissingMethodException: Method not found: '!0[] MediaBrowser.Model.Querying.QueryResult`1.get_Items()'.
   at Jellyfin.Plugin.Reports.Api.ReportsService.GetReportResult(GetItemReport request, User user)
   at Jellyfin.Plugin.Reports.Api.ReportsService.Get(GetItemReport request)
   at lambda_method(Closure , Object , Object )
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)`

**Comment by anthonylavado** [comment]
Version 4 has been released. Could you try that and let us know if you're still having issues?

**Comment by malikaygar** [comment]
yeah so its still not working
