### ISSUE TITLE
Only activity works

### ISSUE THREAD

**Issue by dga4130-renato** [jellyfin/jellyfin-plugin-reports#20]
Running on ubuntu 19.10.
plugin installed but only working for activity.
![Schermata del 2020-03-25 07-43-50](https://user-images.githubusercontent.com/43514633/77509388-e5413280-6e6c-11ea-942c-9401cfec7be5.png)

**Comment by dga4130-renato** [comment]
[2020-03-25 07:51:07.272 +01:00] [ERR] Error processing request
System.MissingMethodException: Method not found: 'MediaBrowser.Controller.Entities.User MediaBrowser.Controller.Library.IUserManager.GetUserById(System.String)'.
   at Jellyfin.Plugin.Reports.Api.ReportsService.Get(GetItemReport request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by DesertCookie** [comment]
I have this problem too with this plugin and the Playback Reporting plugin too, for that matter. The page just turns up empty.
