### ISSUE TITLE
Reports plugin not working in 10.8.0

### ISSUE THREAD

**Issue by Oatavandi** [jellyfin/jellyfin-plugin-reports#67]
Jellyfin Version: 10.8.0
Synology NAS - Docker
Reports Plugin Version: 14.0.0.0
Client Browser: Safari 15.4 (macOS 12.3.1)

Below Error only with Mediatype - **Movies**, **Songs**, **Episodes**, 

----------------------------------------------------------------
```
[2022-06-11 23:11:49.248 +08:00] [ERR] [39] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Reports/Items".
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Model.Entities.MediaStream> MediaBrowser.Model.Dto.MediaSourceInfo.get_MediaStreams()'.
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetStream(BaseItem item, MediaStreamType streamType)
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetVideoStream(BaseItem item)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.<GetOption>b__4_33(BaseItem i, ReportRow r)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetReportRows(IEnumerable`1 items, List`1 options)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetResult(IReadOnlyList`1 items, IReportsQuery request)
   at Jellyfin.Plugin.Reports.Api.ReportsService.GetReportResult(GetItemReport request, User user)
   at Jellyfin.Plugin.Reports.Api.ReportsService.Get(GetItemReport request)
   at Jellyfin.Plugin.Reports.Api.ReportsController.GetItemReport(Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, String adjacentTo, Nullable`1 minIndexNumber, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, String locationTypes, String excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaried, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 airedDuringSeason, String minPremiereDate, String minDateLastSaved, String minDateLastSavedForUser, String maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Nullable`1 isInBoxSet, String excludeItemIds, Nullable`1 enableTotalRecordCount, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String sortOrder, String parentId, String fields, String excludeItemTypes, String includeItemTypes, String filters, Nullable`1 isFavorite, Nullable`1 isNotFavorite, String mediaTypes, String imageTypes, String sortBy, Nullable`1 isPlayed, String genres, String genreIds, String officialRatings, String tags, String years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, String enableImageTypes, String person, String personIds, String personTypes, String studios, String studioIds, String artists, String excludeArtistIds, String artistIds, String albums, String albumIds, String ids, String videoTypes, String userId, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 is3D, String seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, String reportView, String displayType, Nullable`1 hasQueryLimit, String groupBy, String reportColumns, Boolean enableImages)
   at lambda_method994(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-06-11 23:11:55.610 +08:00] [ERR] [36] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Reports/Items".
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Model.Entities.MediaStream> MediaBrowser.Model.Dto.MediaSourceInfo.get_MediaStreams()'.
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetStream(BaseItem item, MediaStreamType streamType)
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetVideoStream(BaseItem item)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.<GetOption>b__4_33(BaseItem i, ReportRow r)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetReportRows(IEnumerable`1 items, List`1 options)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetResult(IReadOnlyList`1 items, IReportsQuery request)
   at Jellyfin.Plugin.Reports.Api.ReportsService.GetReportResult(GetItemReport request, User user)
   at Jellyfin.Plugin.Reports.Api.ReportsService.Get(GetItemReport request)
   at Jellyfin.Plugin.Reports.Api.ReportsController.GetItemReport(Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, String adjacentTo, Nullable`1 minIndexNumber, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, String locationTypes, String excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaried, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 airedDuringSeason, String minPremiereDate, String minDateLastSaved, String minDateLastSavedForUser, String maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Nullable`1 isInBoxSet, String excludeItemIds, Nullable`1 enableTotalRecordCount, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String sortOrder, String parentId, String fields, String excludeItemTypes, String includeItemTypes, String filters, Nullable`1 isFavorite, Nullable`1 isNotFavorite, String mediaTypes, String imageTypes, String sortBy, Nullable`1 isPlayed, String genres, String genreIds, String officialRatings, String tags, String years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, String enableImageTypes, String person, String personIds, String personTypes, String studios, String studioIds, String artists, String excludeArtistIds, String artistIds, String albums, String albumIds, String ids, String videoTypes, String userId, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 is3D, String seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, String reportView, String displayType, Nullable`1 hasQueryLimit, String groupBy, String reportColumns, Boolean enableImages)
   at lambda_method994(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-06-11 23:12:02.465 +08:00] [ERR] [35] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Reports/Items".
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Model.Entities.MediaStream> MediaBrowser.Model.Dto.MediaSourceInfo.get_MediaStreams()'.
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetStream(BaseItem item, MediaStreamType streamType)
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetVideoStream(BaseItem item)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.<GetOption>b__4_33(BaseItem i, ReportRow r)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetReportRows(IEnumerable`1 items, List`1 options)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetResult(IReadOnlyList`1 items, IReportsQuery request)
   at Jellyfin.Plugin.Reports.Api.ReportsService.GetReportResult(GetItemReport request, User user)
   at Jellyfin.Plugin.Reports.Api.ReportsService.Get(GetItemReport request)
```

**Comment by gfxlight55** [comment]
Confirmed in Official 10.8.0 Release of Jellyfin for Windows (Server). It will load User Activity Data but nothing else. All other data points produce error below.

Version: 10.8.0
Operating System: Windows
Architecture: X64

Error in Reporting Plugin:

[23:56:35] [ERR] [30] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /Reports/Items.
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Model.Entities.MediaStream> MediaBrowser.Model.Dto.MediaSourceInfo.get_MediaStreams()'.
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetStream(BaseItem item, MediaStreamType streamType)
   at Jellyfin.Plugin.Reports.Api.Common.ReportBuilderBase.GetVideoStream(BaseItem item)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.<GetOption>b__4_33(BaseItem i, ReportRow r)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetReportRows(IEnumerable`1 items, List`1 options)
   at Jellyfin.Plugin.Reports.Api.Data.ReportBuilder.GetResult(IReadOnlyList`1 items, IReportsQuery request)
   at Jellyfin.Plugin.Reports.Api.ReportsService.GetReportResult(GetItemReport request, User user)
   at Jellyfin.Plugin.Reports.Api.ReportsService.Get(GetItemReport request)
   at Jellyfin.Plugin.Reports.Api.ReportsController.GetItemReport(Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, String adjacentTo, Nullable`1 minIndexNumber, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, String locationTypes, String excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaried, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 airedDuringSeason, String minPremiereDate, String minDateLastSaved, String minDateLastSavedForUser, String maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Nullable`1 isInBoxSet, String excludeItemIds, Nullable`1 enableTotalRecordCount, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String sortOrder, String parentId, String fields, String excludeItemTypes, String includeItemTypes, String filters, Nullable`1 isFavorite, Nullable`1 isNotFavorite, String mediaTypes, String imageTypes, String sortBy, Nullable`1 isPlayed, String genres, String genreIds, String officialRatings, String tags, String years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, String enableImageTypes, String person, String personIds, String personTypes, String studios, String studioIds, String artists, String excludeArtistIds, String artistIds, String albums, String albumIds, String ids, String videoTypes, String userId, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 is3D, String seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, String reportView, String displayType, Nullable`1 hasQueryLimit, String groupBy, String reportColumns, Boolean enableImages)
   at lambda_method1112(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

**Comment by VigibotDev** [comment]
Same problem with debian package, server upgraded to 1.8.0 stable today and broken plugin Reports. same problem with uninstall and install the plugin.

**Comment by funkybunch** [comment]
Same for me.  Busted on 10.8.0 & 10.8.1 running on Docker.

**Comment by Oatavandi** [comment]
Works now

**Comment by VigibotDev** [comment]
Just tested, it works now. Thanks
