### ISSUE TITLE
Plugin version 16 not compatible with Jellyfin 10.9

### ISSUE THREAD

**Issue by foux** [jellyfin/jellyfin-plugin-reports#83]
Hi there!
As plugin version 16 was just deployed, I assumed it would be compatible with Jellyfin 10.9. Unfortuantely it isn't : 
![CleanShot 2024-05-11 at 22 01 35](https://github.com/jellyfin/jellyfin-plugin-reports/assets/246550/8675a89c-f5ce-4e23-b84b-fafbad557e73)

Thanks!

**Comment by crobibero** [comment]
Please provide logs as this screenshot is not helpful

**Comment by foux** [comment]
Sorry about that, here are the error logs : 
```
[2024-05-11 21:47:28.398 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca" from "/config/data/plugins/Reports_16.0.0.0/ExcelNumberFormat.dll"
[2024-05-11 21:47:28.414 +02:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/data/plugins/Reports_16.0.0.0/ClosedXML.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.IO.FileNotFoundException: Could not load file or assembly 'SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13'. The system cannot find the file specified.
```

I'm running on jellyfin docker image.
Thanks

**Comment by crobibero** [comment]
Please try v17 which was just released

**Comment by foux** [comment]
I can't find v17 even after rebooting. Has it been released?

**Comment by crobibero** [comment]
May take a little bit to sync around the globe, the plugin can also be manually downloaded from the release: https://github.com/jellyfin/jellyfin-plugin-reports/releases/tag/v17

**Comment by foux** [comment]
Working. Thanks for the quick fix @crobibero
